### ISSUE TITLE
Interval on computed property macros fromNow and toNow

### ISSUE THREAD

**Issue by cristinawithout** [adopted-ember-addons/ember-moment#153]
There appears to be a way to update the from now and to now helpers at a given interval but I don't see a way to do the same for the computed properties.

**Comment by jasonmit** [comment]
There isn't an API for this for now, but I would live to see this feature as well.

**Comment by lolmaus** [comment]
> There appears to be a way to update the from now and to now helpers at a given interval 

How can I do that?

**Comment by lolmaus** [comment]
Ok, this undocumented approach worked for me:

    {{moment-from-now (moment timeMs) (now interval=1000)}}

This also works, kinda documented:

    {{moment-duration (moment-diff (moment timeMs) (now interval=1000))}}

**Comment by jasonmit** [comment]
@lolmaus feel free to send a PR to update the docs where you feel it's lacking.

**Comment by NullVoxPopuli** [comment]
computed property macros have been removed in v9
