### ISSUE TITLE
Apply readOnly to all computeds

### ISSUE THREAD

**Issue by kellyselden** [adopted-ember-addons/ember-moment#214]
The industry is moving towards readOnly computed macros:
https://github.com/emberjs/ember.js/issues/9290
https://github.com/stefanpenner/ember-improved-cp#readonly-by-default
https://github.com/kellyselden/ember-awesome-macros/blob/8b38a000e4248d2855e15081af9553bee63abe88/addon/utils.js#L18

Just want to suggest doing it here too. Would be a breaking change.

In awesome macros, I escape the setting via [writable](https://github.com/kellyselden/ember-awesome-macros/blob/8b38a000e4248d2855e15081af9553bee63abe88/addon/writable.js). I can expose this to our common helper, which would be opt-in setting for people that want it here.

**Comment by jasonmit** [comment]
Sounds good, we should add some deprecation warnings ahead of it.

**Comment by NullVoxPopuli** [comment]
computed macros have been removed in v9 :D
