### ISSUE TITLE
global allowEmpty not respected in computed macros

### ISSUE THREAD

**Issue by arschmitz** [adopted-ember-addons/ember-moment#221]
Even with the global allowEmpty set to true the computed macros still output invalid date when there is no input value

**Comment by jasonmit** [comment]
Yes, this is a known limitation and reflected in the README around allowEmpty.  In any case, I would like to support this.

**Comment by arschmitz** [comment]
Maybe i'm crazy but i don't see any notes in the readme that this does not work with computed macros.

**Comment by jasonmit** [comment]
> If null, undefined, or an empty string as a date to any of the moment helpers then you you will Invalid Date in the output. To avoid this issue globally, you can set the option allowEmpty which all of the helpers respect and will result in nothing being rendered instead of Invalid Date.

I just mention moment helper will respect it.

**Comment by NullVoxPopuli** [comment]
computed macros have been removed in v9
