### ISSUE TITLE
diff computed property and helpers

### ISSUE THREAD

**Issue by notacoat** [adopted-ember-addons/ember-moment#240]
any plans on adding diff (https://momentjs.com/docs/#/displaying/difference/)?

**Comment by jasonmit** [comment]
@EmilyBarbour would happily review a PR that adds this.

**Comment by jasonmit** [comment]
Thanks for landing the helper portion of this issue: https://github.com/stefanpenner/ember-moment/pull/241/files

**Comment by EmilyBarbour** [comment]
If no one picks this up, will do in the next couple of weeks; just a bit busy now with work and have more of an immediate need for the helper.

**Comment by jasonmit** [comment]
@EmilyBarbour no rush :)  If I can carve out time between now and then I'll also jump in.

**Comment by NullVoxPopuli** [comment]
computed macros have been removed in v9 -- this can be handled via a plain ol' JS getter
