### ISSUE TITLE
`services/moment.js` bug in `defaultFormat`

### ISSUE THREAD

**Issue by jfdnc** [adopted-ember-addons/ember-moment#362]
`9.0.0` release includes update to `MomentService.defaultFormat`

https://github.com/adopted-ember-addons/ember-moment/blob/1adc5afc20526af59bde67c7fa8b3e01b9a04971/app/services/moment.js#L5

which is resulting in `TypeError: Cannot read property 'outputFormat' of undefined` if `config.moment` isn't defined in the consuming app.

[Previous implementation](https://github.com/adopted-ember-addons/ember-moment/blame/ecab65939eb3046979a3682124c83edbefad2eb5/app/services/moment.js#L8) was just silently passing through on this due to `get`, I believe.

Am I missing something config-wise or are other people experiencing this with the `9.0.0` release?

**Comment by Techn1x** [comment]
I have also hit this same error. It also occurs when using the moment helper, if you use it without an output format like this:
```hbs
{{moment this.someDate "dd-mm-yyyy"}}
```

(it's expecting both an input and output format)

**Comment by davideferre** [comment]
The same for me.
Maybe the PR #363 can be improved using the moment default format specified in docs ["Default format" subsection](https://momentjs.com/docs/#/displaying/format/)

**Comment by jfdnc** [comment]
@davideferre I believe that passing `null` is sufficient for allowing `moment` to default to ISO8601. Explicitly passing that string as a default here would be overspecifying. Previous implementation fell back to `null` in a similar manner to https://github.com/adopted-ember-addons/ember-moment/pull/363
