### ISSUE TITLE
moment-timezone dependency added

### ISSUE THREAD

**Issue by Techn1x** [adopted-ember-addons/ember-moment#366]
The 9.0.0 release seemed to add moment-timezone as a dependency (adding about 30kb compressed to bundle size) - was this intentional? It isn't listed in the changelog, and I don't have this configuration set
https://github.com/adopted-ember-addons/ember-moment#include-moment-timezone

It looks like it was added to the package.json dependencies as part of this PR?
https://github.com/adopted-ember-addons/ember-moment/pull/355

**Comment by Techn1x** [comment]
When I add this to my config, it still seems to include it
```js
moment: {
  includeTimezone: 'none',
},
```

Is anyone else seeing this?

**Comment by jfdnc** [comment]
@Techn1x I think this was a side-effect of the [removal of `ember-cli-moment-shim`](https://github.com/adopted-ember-addons/ember-moment/commit/0f02477277b207e8035575df260329d5c17037e2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L45).  That library was handling both [`includeTimezone` and `includeLocales`](https://github.com/jasonmit/ember-cli-moment-shim/blob/010c9ba0d0665d706ab60787c00d9ee9db0465d7/index.js#L65-L66), so the documentation in this repo needs to be updated and/or a path should exposed here to conditionally include those extra features if possible. I'm not a maintainer here, just like to poke around when I have some free time. I'll take a look and see if there are some obvious paths forward!

**Comment by jfdnc** [comment]
It looks like the [`moment` service](https://github.com/adopted-ember-addons/ember-moment/blob/1adc5afc20526af59bde67c7fa8b3e01b9a04971/addon/services/moment.js#L4) is directly importing `moment-timezone`, which also pulls in the base library.  This library is already using `ember-auto-import`, so I don't see why we couldn't [dynamically import](https://github.com/ef4/ember-auto-import#dynamic-import) either the base library (when the config var is 'none') or `moment-timezone` if needed. Will explore that a bit.
