### ISSUE TITLE
Environment configuration does not work as documented

### ISSUE THREAD

**Issue by mayatron** [adopted-ember-addons/ember-moment#375]
The `README.md` shows the following example configuration for the `allowEmpty` option:

```js
// config/environment.js
module.exports = function() {
  return {
    moment: {
      allowEmpty: true // default: false
    }
  }
};
```

However, this does not seem to work for me, unless I change the key from `moment` to `'ember-moment'` like this:

```js
// config/environment.js
module.exports = function() {
  return {
    'ember-moment': {
      allowEmpty: true // default: false
    }
  }
};
```

Additionally, the application config appears to point to `ember-moment` as the expected key in multiple places:

- https://github.com/adopted-ember-addons/ember-moment/blob/c80dd174c034d1ad62d2e016ea46d7de05d4cf98/src/services/moment.js#L23
- https://github.com/adopted-ember-addons/ember-moment/blob/c80dd174c034d1ad62d2e016ea46d7de05d4cf98/test-app/config/environment.js#L9

Am I missing something? Or should we update the README from `moment` to `'ember-moment'`?

**Comment by MikiDi** [comment]
I'm experiencing this as well (`ember-moment v10.0.0`). Config in `config/environment.js` is not picked up by key `moment`, but `ember-moment`. May I suggest broadening the title of this issue @mayatron ?

**Comment by mayatron** [comment]
> I'm experiencing this as well (`ember-moment v10.0.0`). Config in `config/environment.js` is not picked up by key `moment`, but `ember-moment`. May I suggest broadening the title of this issue @mayatron ?

Done!

**Comment by NullVoxPopuli** [comment]
docs updated, thanks!
