### ISSUE TITLE
Documentation incorrect for environment settings

### ISSUE THREAD

**Issue by Synforge** [adopted-ember-addons/ember-moment#391]
In the documentation it seems to state that to change various defaults you should set 'moment' in your env, however it seems like instead this should be 'ember-moment' after reading the source (https://github.com/adopted-ember-addons/ember-moment/blob/master/src/services/moment.js#L23).

For example, this doesn't work:
```
moment: {
      outputFormat: 'YYYY-MM-DD HH:mm:ss',
},
```

But this does:
```
'ember-moment': {
      outputFormat: 'YYYY-MM-DD HH:mm:ss',
},
```

**Comment by NullVoxPopuli** [comment]
docs updated, thanks!
